// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from '/root/.openclaw/workspace-vest/promo-data-analyzer/frontend-pro/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import DatabaseOutlined from '/root/.openclaw/workspace-vest/promo-data-analyzer/frontend-pro/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DatabaseOutlined';
import BarChartOutlined from '/root/.openclaw/workspace-vest/promo-data-analyzer/frontend-pro/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/BarChartOutlined';
import RobotOutlined from '/root/.openclaw/workspace-vest/promo-data-analyzer/frontend-pro/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/RobotOutlined';
import MonitorOutlined from '/root/.openclaw/workspace-vest/promo-data-analyzer/frontend-pro/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/MonitorOutlined';
import SettingOutlined from '/root/.openclaw/workspace-vest/promo-data-analyzer/frontend-pro/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/SettingOutlined';
export default { DashboardOutlined, DatabaseOutlined, BarChartOutlined, RobotOutlined, MonitorOutlined, SettingOutlined };
